### ISSUE TITLE
Update to 8.6

### ISSUE THREAD

**Issue by virtualirfan** [DefinitelyScala/scala-js-auth0js#1]
Hi:

As per this [commit](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/524b072a5afa4ae9583a515dd5d44ce1d050ed5c), the DefinitelyTyped auth0-js facade has recently been updated. One nice thing out of that is more detailed nested type annotations.

Could you please rerun and update to this new version? Or if you prefer to see a PR, please share how to do that … I didn't immediately find how you run your scripts to generate PRs.

**Comment by KyleU** [comment]
I had no idea folks were making issues for this stuff, sorry for the delay. I am auto-generating these projects, once every few months. Working on open sourcing the translator soon.
